model:
  image_channels: 3

  lam_model_dim: 512
  lam_latent_dim: 128
  lam_num_latents: 32
  lam_patch_size: 8
  lam_enc_blocks: 8
  lam_dec_blocks: 8
  lam_num_heads: 8

  vq_beta: 0.25
  log_interval: 10000
  log_path: /mnt/workspace/qwbu/OmniEmbodiment/logs
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 5e-5
      weight_decay: 1e-2

  task_name: lam_openx
  make_data_pair: &make_data_pair false

data:
  data_root: /cpfs01/shared/opendrivelab/opendrivelab_hdd/OpenX_all
  data_mix: oxe_magic_soup_plus
  batch_size: 16
  resolution: 128
  num_frames: 16  # TODO
  episodic: false
  shuffle_buffer_size: 1000
  image_aug: true

trainer:
  max_epochs: 5
  accelerator: gpu
  num_nodes: 1
  devices: 8
  strategy: ddp_find_unused_parameters_false
  precision: 16-mixed
  log_every_n_steps: 1000
  gradient_clip_val: 0.3

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: /mnt/workspace/qwbu/OmniEmbodiment/logs/ckpts_openx
        verbose: true
        save_last: true
        save_top_k: -1

  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: /mnt/workspace/qwbu/OmniEmbodiment/logs
        name: lam_openx
