model:
  image_channels: 3

  lam_model_dim: 512
  lam_latent_dim: 128
  lam_num_latents: 32
  lam_patch_size: 14
  lam_enc_blocks: 8
  lam_dec_blocks: 8
  lam_num_heads: 8

  vq_beta: 0.25
  log_interval: 5000
  log_path: /cpfs01/user/buqingwen/OmniEmbodiment/logs
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1.5e-4
      weight_decay: 1e-2

  task_name: stage1_lam_openx_v2
  make_data_pair: &make_data_pair false
  control_aware: true

data:
  data_root: /cpfs01/shared/opendrivelab/opendrivelab_hdd/OpenX_all
  data_mix: oxe_magic_soup_plus
  batch_size: 64
  resolution: 224
  num_frames: 16  # TODO
  episodic: false
  shuffle_buffer_size: 1000
  image_aug: true

trainer:
  max_epochs: 10
  accelerator: gpu
  num_nodes: 1
  devices: 1
  strategy: ddp_find_unused_parameters_false
  precision: 16-mixed
  log_every_n_steps: 5000
  gradient_clip_val: 0.3

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: /cpfs01/user/buqingwen/OmniEmbodiment/logs/stage1_ckpts_openx_v2
        verbose: true
        save_last: true
        save_top_k: -1
        every_n_train_steps: 5000

  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: /cpfs01/user/buqingwen/OmniEmbodiment/logs
        name: stage1_lam_openx_v2
